name: Nuclei Latest Templates

on:
   schedule:
     - cron: '1 0 * * *'
   workflow_dispatch:
jobs:
  app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
    #ec106b438a1ff6ff109590de34ddc62c540232e0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
    - name: Install dependencies
      run: gem install open-uri
    - name: Run app
      run: |
        ruby ./tools/nuclei-latest.rb
  CI:
    runs-on: ubuntu-latest
    needs: [app]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Commit files
      run: |
        git config --local user.email "hahwul@gmail.com"
        git config --local user.name "hahwul"
        git add docs/nuclei-latest.json
        git commit -m "Updated"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
